# fix_master.py
"""
Repairs the Hyderabad 150-ward master dataset.

Outputs:
  hyderabad_150_ward_SUPER_wide_worldpop_v3.csv
  hyderabad_150_ward_SUPER_panel_worldpop_v3.csv
  fix_log.txt

Does NOT touch any value that is a real observation.
Only fixes structure, naming, coverage scoring, and panel layout.
"""
import os, re, sys
import numpy as np
import pandas as pd

BASE = os.path.dirname(os.path.abspath(__file__))
WIDE_IN  = os.path.join(BASE, "hyderabad_150_ward_SUPER_wide_worldpop_v2.csv")
PANEL_IN = os.path.join(BASE, "hyderabad_150_ward_SUPER_panel_worldpop_v2.csv")
WIDE_OUT = os.path.join(BASE, "hyderabad_150_ward_SUPER_wide_worldpop_v3.csv")
PANEL_OUT= os.path.join(BASE, "hyderabad_150_ward_SUPER_panel_worldpop_v3.csv")
LOG      = os.path.join(BASE, "fix_log.txt")

log_lines = []
def log(m):
    print(m)
    log_lines.append(m)

# ------------------------------------------------------------------
# Load
# ------------------------------------------------------------------
if not os.path.exists(WIDE_IN):
    sys.exit(f"Missing {WIDE_IN}")

wide = pd.read_csv(WIDE_IN, low_memory=False)
log(f"[wide] loaded {wide.shape[0]} rows x {wide.shape[1]} cols")

if wide.shape[0] != 150:
    log(f"[wide] WARNING: expected 150 rows, got {wide.shape[0]}")

# ------------------------------------------------------------------
# FIX 4 — collapse doubled census2011_ prefix
# ------------------------------------------------------------------
doubled = [c for c in wide.columns if c.startswith("census2011_census2011_")]
if doubled:
    rename_map = {c: "census2011_" + c[len("census2011_census2011_"):] for c in doubled}
    # If the un-doubled name already exists as a real column, we must not
    # overwrite it — check first.
    colliding = [v for v in rename_map.values() if v in wide.columns and v not in rename_map]
    if colliding:
        log(f"[wide] WARNING: {len(colliding)} renamed columns would collide; "
            f"dropping the doubled copies instead.")
        wide = wide.drop(columns=[k for k, v in rename_map.items() if v in colliding])
        rename_map = {k: v for k, v in rename_map.items() if v not in colliding}
    wide = wide.rename(columns=rename_map)
    log(f"[wide] renamed {len(rename_map)} doubled-prefix columns")
else:
    log("[wide] no doubled census2011_ prefixes found (already fixed)")

# ------------------------------------------------------------------
# FIX 5 — ward naming: 31 -> Rein Bazar, 37 -> Kurmaguda
#   Evidence: the uploaded GeoJSON contains
#     relation/7861529  name="Ward 31 Rein Bazar"  (+ worldpop_geometry_note)
#     relation/7861530  name="Ward 37 Kurmaguda"
#   So the OSM "Ward 37 Rein Bazar" was a mislabel of ward 31.
# ------------------------------------------------------------------
if "ward_name_readme" in wide.columns:
    mask31 = wide["ward_id"] == 31
    mask37 = wide["ward_id"] == 37
    old31 = wide.loc[mask31, "ward_name_readme"].astype(str).values
    old37 = wide.loc[mask37, "ward_name_readme"].astype(str).values
    wide.loc[mask31, "ward_name_readme"] = "Rein Bazar"
    wide.loc[mask37, "ward_name_readme"] = "Kurmaguda"
    log(f"[wide] ward 31 name: {old31} -> 'Rein Bazar'")
    log(f"[wide] ward 37 name: {old37} -> 'Kurmaguda'")
else:
    log("[wide] no ward_name_readme column — skipping ward rename")

# ------------------------------------------------------------------
# FIX 1b — drop WorldPop placeholder years that are 100% empty.
#   We only have 2015 and 2018 rasters. Columns 2016, 2017, 2019-2030
#   were created as placeholders and never populated.
# ------------------------------------------------------------------
wp_placeholder_cols = []
for c in wide.columns:
    m = re.fullmatch(r"worldpop_population_(\d{4})", c)
    if m:
        yr = int(m.group(1))
        if yr not in (2015, 2018) and wide[c].isna().all():
            wp_placeholder_cols.append(c)
if wp_placeholder_cols:
    wide = wide.drop(columns=wp_placeholder_cols)
    log(f"[wide] dropped {len(wp_placeholder_cols)} empty worldpop year columns "
        f"(2016,2017,2019-2030) — will be regenerated by forecasting stage")

# Also drop the corresponding growth cols for those empty years
growth_placeholders = [c for c in wide.columns
                       if re.match(r"worldpop_(abs|pct)_growth_\d{4}$", c)
                       and wide[c].isna().all()]
if growth_placeholders:
    wide = wide.drop(columns=growth_placeholders)
    log(f"[wide] dropped {len(growth_placeholders)} empty worldpop growth cols")

# ------------------------------------------------------------------
# FIX 6 — recompute data_coverage_score to include WorldPop.
#   4 signals: census 2011, udise 2021-22, udise 2023-24, worldpop 2015/2018
# ------------------------------------------------------------------
def _has_census(row):
    for c in ("census2011_population_verified", "census2011_census2011_population_verified"):
        if c in wide.columns and pd.notna(row.get(c)):
            return 1
    return 0

def _has_udise21(row):
    c = "udise2021_22_data_available"
    return 1 if c in wide.columns and pd.notna(row.get(c)) and row.get(c) == 1 else 0

def _has_udise23(row):
    c = "udise2023_24_data_available"
    return 1 if c in wide.columns and pd.notna(row.get(c)) and row.get(c) == 1 else 0

def _has_wp(row):
    return 1 if pd.notna(row.get("worldpop_population_2015")) else 0

cov = wide.apply(lambda r: (_has_census(r) + _has_udise21(r) + _has_udise23(r) + _has_wp(r)) / 4.0,
                 axis=1)
old_cov = wide["data_coverage_score"].copy() if "data_coverage_score" in wide.columns else None
wide["data_coverage_score"] = cov
log(f"[wide] recomputed data_coverage_score over 4 signals (was 3, ignored WorldPop)")
if old_cov is not None:
    changed = (old_cov != wide["data_coverage_score"]).sum()
    log(f"[wide] coverage_score changed for {changed} wards")

# ------------------------------------------------------------------
# Save wide
# ------------------------------------------------------------------
wide.to_csv(WIDE_OUT, index=False)
log(f"[wide] wrote {WIDE_OUT}  shape={wide.shape}")

# ------------------------------------------------------------------
# FIX 2 & 3 — rebuild the panel with correct year alignment.
#   Layout:
#     2011 row  -> census columns only
#     2015 row  -> worldpop_population only
#     2018 row  -> worldpop_population only
#     2021 row  -> udise_* (mapped from udise2021_22_*)
#     2023 row  -> udise_* (mapped from udise2023_24_*)
#   No cross-year leakage: Census values appear ONLY on the 2011 row.
# ------------------------------------------------------------------
census_cols = [c for c in wide.columns if c.startswith("census2011_")]
wp_cols     = [c for c in wide.columns if c.startswith("worldpop_")
               and not c.startswith("worldpop_abs_growth")
               and not c.startswith("worldpop_pct_growth")
               and not c.startswith("worldpop_annualized")
               and c not in ("worldpop_status",)]
udise21_cols = [c for c in wide.columns if c.startswith("udise2021_22_")]
udise23_cols = [c for c in wide.columns if c.startswith("udise2023_24_")]

def _udise_base(col, prefix):
    """Strip 'udise2021_22_' or 'udise2023_24_' -> return 'udise_<suffix>'."""
    return "udise_" + col[len(prefix):]

rows = []
for _, w in wide.iterrows():
    wid = w["ward_id"]
    wn  = w.get("ward_name_readme")

    # --- 2011: census only
    r = {"ward_id": wid, "year": 2011, "ward_name": wn}
    for c in census_cols:
        r[c] = w[c]
    rows.append(r)

    # --- 2015: WorldPop only
    r = {"ward_id": wid, "year": 2015, "ward_name": wn,
         "worldpop_population": w.get("worldpop_population_2015")}
    rows.append(r)

    # --- 2018: WorldPop only
    r = {"ward_id": wid, "year": 2018, "ward_name": wn,
         "worldpop_population": w.get("worldpop_population_2018")}
    rows.append(r)

    # --- 2021: UDISE 2021-22 only
    r = {"ward_id": wid, "year": 2021, "ward_name": wn,
         "udise_source_year": "2021-22"}
    for c in udise21_cols:
        r[_udise_base(c, "udise2021_22_")] = w[c]
    rows.append(r)

    # --- 2023: UDISE 2023-24 only
    r = {"ward_id": wid, "year": 2023, "ward_name": wn,
         "udise_source_year": "2023-24"}
    for c in udise23_cols:
        r[_udise_base(c, "udise2023_24_")] = w[c]
    rows.append(r)

panel = pd.DataFrame(rows)
panel = panel.sort_values(["ward_id", "year"]).reset_index(drop=True)

expected = 150 * 5
if len(panel) != expected:
    log(f"[panel] WARNING: expected {expected} rows, got {len(panel)}")
else:
    log(f"[panel] rebuilt: {len(panel)} rows = 150 wards x 5 years")

# Sanity: no census values on non-2011 rows
non2011 = panel[panel["year"] != 2011]
if "census2011_population_verified" in non2011.columns:
    leak = non2011["census2011_population_verified"].notna().sum()
    if leak:
        log(f"[panel] ERROR: {leak} census values leaked onto non-2011 rows")
    else:
        log("[panel] leakage check PASS: census values only on 2011 rows")

panel.to_csv(PANEL_OUT, index=False)
log(f"[panel] wrote {PANEL_OUT}  shape={panel.shape}")

# ------------------------------------------------------------------
# Log
# ------------------------------------------------------------------
with open(LOG, "w") as f:
    f.write("\n".join(log_lines))
print(f"\nAll fixes applied. Log: {LOG}")